coverage:
  precision: 2
  round: down
  range: "0...100"

  ignore:
    - Example
    - Tests
    - Library/Sources/Utils/WebViewWrapper*
    - Library/Sources/Utils/Reachability.swift
    - Library/Sources/SDK/UI/CaptchaController*
    - Library/Sources/SDK/UI/WebController*
