coverage:
  precision: 2
  round: up
  range: "75...100"

  ignore:
    - Example
    - Tests
    - Library/Sources/UI/*/*Controller*
    - Library/Sources/UI/Web/WebViewWrapper*
    - Library/Sources/Utils/Reachability.swift
    - Library/Sources/Utils/IDGenerator.swift
    - Library/Sources/Extensions/Numbers+Extensions.swift
    - Library/Sources/Extensions/URLOpener.swift
    - Library/Sources/Extensions/VKURLSession.swift
