language: objective-c
os: osx
osx_image: xcode9
xcode_sdk: iphonesimulator10.2

branches:
  only:
    - master
    - v3

before_script:
  - set -o pipefail

jobs:
  include:
    - stage: test
      env: JOB=SwiftLint
      script:
        - swiftlint lint --path Library --strict
    - stage: test
      env: JOB=Test SwiftyVK macOS
      script:
        - xcodebuild -workspace SwiftyVK.xcworkspace -scheme SwiftyVK_macOS -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" ENABLE_TESTABILITY=YES test | xcpretty -f `xcpretty-travis-formatter`
        - bash <(curl -s https://codecov.io/bash)
    - stage: test
      env: JOB=Test SwiftyVK iOS
      script:
        - xcodebuild -workspace SwiftyVK.xcworkspace -scheme SwiftyVK_iOS -destination "platform=iOS Simulator,name=iPhone 7 Plus" -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" test | xcpretty -f `xcpretty-travis-formatter`
    - stage: test
      env: JOB=Pod lib lint
      script:
        - pod lib lint
