language: objective-c
os: osx
osx_image: xcode9
xcode_sdk: iphonesimulator10.2

branches:
  only:
    - master
    - v3

env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8

jobs:
  include:
    - stage: test
      env: JOB=SwiftLint
      script: swiftlint lint --path Library --strict
    - stage: test
      env: JOB=MacOS test
      script: ./Scripts/macOS-tests.sh
    - stage: test
      env: JOB=iOS test
      script: ./Scripts/iOS-tests.sh
    - stage: test
      env: JOB=Pod lint
      script: pod lib lint
    - stage: deploy
      env: JOB=Codecov
      script: bash <(curl -s https://codecov.io/bash)
