excluded:
  - Carthage
  - Pods

disabled_rules:
  - trailing_whitespace
  - vertical_whitespace
  - nesting
  - variable_name
  - type_name

opt_in_rules:
  - private_outlet
  - overriden_super_call
# vertical_whitespace:
#   maxEmptyLines: 3
line_length:
  warning: 200
  error: 300
function_body_length:
  warning: 100
  error: 150
file_length:
  warning: 500
  error: 1500
variable_name:
  min_length:
    warning: 2
    error: 2
  max_length:
    warning: 50
    error: 100
cyclomatic_complexity:
  warning: 20
  error: 30
